HOSTS:
  ubuntu-12.04-64:
    roles:
      - agent
    platform: ubuntu-12.04-64
    box : ubuntu12.04puppet
    box_url : https://vagrantcloud.com/puppetlabs/ubuntu-12.04-64-puppet/version/3/provider/virtualbox.box
    hypervisor : vagrant
CONFIG:
  log_level: debug
  type: foss
